failre removed

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,7 +26,7 @@ jobs:
     steps:
       - name: Stage 2 Step
         run: echo "Stage 2 completed successfully"
-        run: exit 1  # Simulating a failure here
+        #run: exit 1  # Simulating a failure here
 
   stage3:
     name: Stage3-Final-Deploy
